CREATE TABLE dr_dates(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    place_id TEXT NOT NULL,
    meal_id TEXT NOT NULL,
    meal_type TEXT NOT NULL,
    drink_id TEXT NOT NULL,
    show_id TEXT NOT NULL,
    show_type TEXT NOT NULL,
    user_id INTEGER REFERENCES dr_users(id) ON DELETE SET NULL
);